analytics: {}
color:
  brandColors:
    - '#005688'
    - '#ffffff'
    - '#3378a0'
    - '#cbdce6'
    - '#5b92b2'
  brandStrength: 0.638513
  lightness: 0.5
  rhythmicContrast: 0.658784
  saturation: 0.4375
cta: {}
layout_spectrum: 0.398649
name: Hackerfleet
opengraph: {}
purpose:
  - name: shares
    item: fda66d88-b1cb-469b-8f4f-9aac505419d6
    url: 'https://www.facebook.com/Hackerfleet'
typography_spectrum: 0.55508
