name: Hackerfleet
favicon: null
layout_spectrum: 0.01934
typography_spectrum: 0.55508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005688'
    - '#ffffff'
    - '#3378a0'
    - '#cbdce6'
    - '#5b92b2'
  brandStrength: 0.638513
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.658784
purpose: []
github: true
