name: null
favicon: null
layout_spectrum: 0.08051
typography_spectrum: 0.55508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005688'
    - '#ffffff'
    - '#3378a0'
    - '#cbdce6'
    - '#5b92b2'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: fda66d88-b1cb-469b-8f4f-9aac505419d6
    url: 'https://www.facebook.com/Hackerfleet'
